/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import static Inicio.Profesores.seleccionado;
import static Inicio.inicio.listaMaterias;
import static Inicio.inicio.listaProfesores;
import Profesor.Materia;
import java.io.FileWriter;
import java.util.LinkedList;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author A8
 */
public class editarProfesor extends javax.swing.JFrame {

     public String materiaselec = "";
    public editarProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
         for (int i = 0; i < listaMaterias.size(); i++) {
            cbxMaterias.addItem(listaMaterias.get(i).getNombre());
        }
        
        for (int i = 0; i < listaProfesores.size(); i++) {
           if (listaProfesores.get(i).getNombre().compareTo(seleccionado) == 0){
              txtNombre.setText(listaProfesores.get(i).getNombre());
              
              
           try{
          
           String nombreColumnas [] ={"Materias"};
           String data [][] = new String [listaProfesores.get(i).getMaterias().size()][1];
         
        for (int j = 0; j < listaProfesores.get(i).getMaterias().size(); j++) {  
            
                   data[j][0] = listaProfesores.get(i).getMaterias().get(j).getNombre();                          
                   tableMaterias.setModel(new DefaultTableModel(data,nombreColumnas));                   
        }
        }catch( Exception a ){}
           }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMaterias = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbxMaterias = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 550));

        jPanel1.setMaximumSize(new java.awt.Dimension(850, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jPanel1.setLayout(null);

        jLabel1.setText("Editar Profesor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 30, 90, 30);

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 110, 50, 14);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(230, 100, 390, 30);

        tableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materias"
            }
        ));
        tableMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMaterias);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 140, 250, 270);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 463, 90, 50);

        jButton2.setText("Eliminar Materia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 420, 120, 30);

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(260, 460, 120, 30);

        jPanel1.add(cbxMaterias);
        cbxMaterias.setBounds(510, 160, 220, 20);

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(740, 160, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                     Profesores Profesores = new Profesores();
                     Profesores.setVisible(true);
                     dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMateriasMouseClicked
       int seleccion = tableMaterias.rowAtPoint(evt.getPoint());
        materiaselec = String.valueOf(tableMaterias.getValueAt(seleccion, 0));     
    }//GEN-LAST:event_tableMateriasMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (materiaselec.compareTo("") == 0 || materiaselec.compareTo("null") == 0 ){
            JOptionPane.showMessageDialog(null, "Seleccione una materia");        
          }else{
              for (int i = 0; i < listaProfesores.size(); i++) {
                   if (listaProfesores.get(i).getNombre().compareTo(seleccionado) == 0){
                       for (int j = 0; j < listaProfesores.get(i).getMaterias().size(); j++) {
                           if (listaProfesores.get(i).getMaterias().get(j).getNombre().compareTo(materiaselec)== 0){
                               listaProfesores.get(i).getMaterias().remove(j);
                               if (listaProfesores.get(i).getMaterias().size() == 0){
                            try{
          
                                String nombreColumnas [] ={"Materias"};
                                String data [][] = new String [0][1];
                         
                                 tableMaterias.setModel(new DefaultTableModel(data,nombreColumnas));                   
             
                            }catch( Exception a ){}
                               }
                           }
                       }
                   }
              }
             
            for (int i = 0; i < listaProfesores.size(); i++) {
           if (listaProfesores.get(i).getNombre().compareTo(seleccionado) == 0){

           try{
          
           String nombreColumnas [] ={"Materias"};
           String data [][] = new String [listaProfesores.get(i).getMaterias().size()][1];
         
        for (int j = 0; j < listaProfesores.get(i).getMaterias().size(); j++) {  
            
                   data[j][0] = listaProfesores.get(i).getMaterias().get(j).getNombre();                          
                   tableMaterias.setModel(new DefaultTableModel(data,nombreColumnas));                   
        }
        }catch( Exception a ){}
           }
        }
              
               JSONArray list = new JSONArray();
               for (int i = 0; i < listaProfesores.size(); i++) {
                JSONObject obj0 = new JSONObject();
		obj0.put("NOMBRE", listaProfesores.get(i).getNombre());
                JSONArray list1 = new JSONArray();
               for (int j = 0; j < listaProfesores.get(i).getMaterias().size(); j++) {
                  JSONObject obj1 = new JSONObject();
		  obj1.put("NOMBRE", listaProfesores.get(i).getMaterias().get(j).getNombre());
                  list1.add(obj1);
               }
		obj0.put("MATERIAS", list1);
               
               list.add(obj0);          
         }

	        JSONObject obj3 = new JSONObject();
		obj3.put("Profesores", list);
		
		try{
			FileWriter file = new FileWriter("Profesores.txt");
			file.write(obj3.toJSONString());
			file.flush();
			file.close();
			
			
		}catch(Exception ex){
			System.out.println("Error: "+ex.toString());
		}
		finally{
			//System.out.println(obj1);
		}
                
                     JOptionPane.showMessageDialog(null, "Eliminado Exitosamente");
                     materiaselec = "";
              
       
          }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String i = cbxMaterias.getSelectedItem().toString();
         if ((i.compareTo("") == 0) || (i == null)){
            JOptionPane.showMessageDialog(null, "Seleccione una Materia por favor !!!");
         }else{
             Materia nueva = new Materia();
             nueva.setNombre(i);
             for (int k = 0; k < listaProfesores.size(); k++) {
                   if (listaProfesores.get(k).getNombre().compareTo(seleccionado) == 0){
                       boolean paso = true;
                       for (int j = 0; j < listaProfesores.get(k).getMaterias().size(); j++) {
                           if (listaProfesores.get(k).getMaterias().get(j).getNombre().compareTo(nueva.getNombre())== 0){
                               paso = false;
                               break;
                           }
                       }
                       if (paso){
                           listaProfesores.get(k).getMaterias().add(nueva);
                       } 
                       
                try{
          
                 String nombreColumnas [] ={"Materias"};
                 String data [][] = new String [listaProfesores.get(k).getMaterias().size()][1];
         
                 for (int j = 0; j < listaProfesores.get(k).getMaterias().size(); j++) {             
                   data[j][0] = listaProfesores.get(k).getMaterias().get(j).getNombre();                          
                   tableMaterias.setModel(new DefaultTableModel(data,nombreColumnas));                   
                 }
               }catch( Exception a ){}
                       
                       
                }
              }
             
             
             

          
         }       
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtNombre.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Rellene el campo del nombre!");
        }else{
            
             for (int i = 0; i < listaProfesores.size(); i++) {
                   if (listaProfesores.get(i).getNombre().compareTo(seleccionado) == 0){
                       listaProfesores.get(i).setNombre(txtNombre.getText());
                       seleccionado = txtNombre.getText();
                       break;
                   }
              }
               JSONArray list = new JSONArray();
               for (int i = 0; i < listaProfesores.size(); i++) {
                JSONObject obj0 = new JSONObject();
		obj0.put("NOMBRE", listaProfesores.get(i).getNombre());
                JSONArray list1 = new JSONArray();
               for (int j = 0; j < listaProfesores.get(i).getMaterias().size(); j++) {
                  JSONObject obj1 = new JSONObject();
		  obj1.put("NOMBRE", listaProfesores.get(i).getMaterias().get(j).getNombre());
                  list1.add(obj1);
               }
		obj0.put("MATERIAS", list1);
               
               list.add(obj0);          
         }

	        JSONObject obj3 = new JSONObject();
		obj3.put("Profesores", list);
		
		try{
			FileWriter file = new FileWriter("Profesores.txt");
			file.write(obj3.toJSONString());
			file.flush();
			file.close();
			
			
		}catch(Exception ex){
			System.out.println("Error: "+ex.toString());
		}
		
                
                JOptionPane.showMessageDialog(null, "Cambios Guardados");
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxMaterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMaterias;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
